#
# https://docs.readthedocs.io/en/stable/config-file/v2.html
#
version: 2

build:
  ##
  # Which OSes are available? See:
  #
  # • https://docs.readthedocs.io/en/stable/config-file/v2.html#build-os
  #
  os: ubuntu-22.04
  tools:
    python: "3.9"
  ##
  # We need this in combination with sphinxcontrib-plantuml (python/pip
  # dependency)so PlantUML diagrams can be generated and embedded into
  # the output during build.
  #
  apt_packages:
    - plantuml

##
# Build documentation in the "docs/source" directory with Sphinx
#
sphinx:
   configuration: docs/source/conf.py
##
# • https://docs.readthedocs.io/en/stable/guides/reproducible-builds.html
#
