@startuml
!includeurl  https://raw.githubusercontent.com/plantuml-stdlib/C4-PlantUML/master/C4_Context.puml
!includeurl  https://raw.githubusercontent.com/plantuml-stdlib/C4-PlantUML/master/C4_Container.puml

'# remove <<system>> above each block
HIDE_STEREOTYPE()


Boundary(protocol, "Protocol / Deidentifier") {
    Container(tags, "Tags", "Transforms DICOM\n metadata") #AA98E2
    Container(filter, "Filter") #A8A8A8
    Container(pixel, "Pixel") #A8A8A8
    Container(private, "Private") #A8A8A8
}

tags -[hidden]r- filter
filter -[hidden]r- pixel
pixel -[hidden]r- private

@enduml