@startuml
!includeurl  https://raw.githubusercontent.com/plantuml-stdlib/C4-PlantUML/master/C4_Context.puml
!includeurl  https://raw.githubusercontent.com/plantuml-stdlib/C4-PlantUML/master/C4_Container.puml

'# remove <<system>> above each block
HIDE_STEREOTYPE()


Boundary(protocol, "Protocol / Deidentifier", "Processes dataset") {
    Container(tags, "Tags", "Transforms DICOM\n metadata") #AA98E2
    Container(filter, "Filter", "Optionally rejects\n dataset") #AA98E2
    Container(pixel, "Pixel", "Processes\n image data") #AA98E2
    Container(private, "Private", "Processes \n private tags") #AA98E2
}

tags -[hidden]r- filter
filter -[hidden]r- pixel
pixel -[hidden]r- private

@enduml
